[package]
name = "replay_downloader"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
